In [13]:
import numpy as np
a=np.zeros((5,20))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [14]:
import numpy as np
a=np.zeros((5,20))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [15]:

import numpy as np
b=np.zeros((8,20))
b


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

# 1. Create a 3x3x3 array with random values




In [21]:
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.49049244 0.82998948 0.74830322]
  [0.17758594 0.85338865 0.66501397]
  [0.00755989 0.86316089 0.50237876]]

 [[0.27666205 0.99164319 0.09753375]
  [0.2026988  0.91089937 0.09352796]
  [0.34223602 0.98131269 0.55369046]]

 [[0.18342242 0.52348977 0.5068997 ]
  [0.82805466 0.56835706 0.65697136]
  [0.41225428 0.63310698 0.09810823]]]


# 2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal


In [28]:
bb=np.zeros((5,5))

np.fill_diagonal(bb[1:], [1,2,3,4])


print(bb)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.create a 8x8 matrix and fill it with a checkerboard pattern

In [36]:
cc=np.zeros((8,8), dtype=int)

cc[::2, ::2] =2
cc[1::2, 1::2] = 3



print(cc)


[[2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]
 [2 0 2 0 2 0 2 0]
 [0 3 0 3 0 3 0 3]]


# 4. Normalise a 5x5 random  matrix

In [43]:

dd = np.random.rand(5, 5)

mean = dd.mean()
std_dev = dd.std()


normalized_matrix = (dd - mean) / std_dev

print("Original Matrix:")
print(dd)

print("\nNormalized Matrix:")
print(normalized_matrix)


Original Matrix:
[[0.00859582 0.33532741 0.92012087 0.35487148 0.52200881]
 [0.25347065 0.87479694 0.44865121 0.72890319 0.77595186]
 [0.78621761 0.76525222 0.59540932 0.04966728 0.83778754]
 [0.45293463 0.01317007 0.78069861 0.25631971 0.22605102]
 [0.62867403 0.98058469 0.93823125 0.1549071  0.43929491]]

Normalized Matrix:
[[-1.71173389 -0.6289541   1.30903586 -0.56418559 -0.0102969 ]
 [-0.90022523  1.15883355 -0.25340204  0.67534554  0.8312636 ]
 [ 0.86528403  0.79580527  0.23295041 -1.57562416  1.03618539]
 [-0.23920689 -1.69657494  0.84699419 -0.89078351 -0.99109316]
 [ 0.34318879  1.50941136  1.36905319 -1.22686222 -0.28440856]]


# 5.How to find common values between two arrays 

In [48]:



e1 = np.array([10,102,568,546,789])
e2 = np.array([259,205,468,458,789, 102])


common_values = np.intersect1d(e1, e2)

print(common_values)


[102 789]


# 6. How to get the dates of yesterday, today and tommorow

In [49]:

import datetime


today = datetime.date.today()


yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7. Consider two random array A and B , check if they are equal 

# 

f1 = np.random.rand(5, 5)
f2 = np.random.rand(6, 6)


are_equal = np.array_equal(f1, f2)

if are_equal:
    print("Arrays f1 and f2 are equal.")
else:
    print("Arrays f1 and f2 are not equal.")


# 8. Create random vector of size 10 and replace the maximnum value by 0


In [60]:


f3 = np.random.rand(10)


max_index = np.argmax(f3)


f3[max_index] = 0

print("Random vector with the maximum value replaced by 0:")
print(f3)


Random vector with the maximum value replaced by 0:
[0.65946847 0.40574427 0.70205197 0.         0.83690278 0.20202443
 0.8993854  0.77784961 0.18348534 0.81698755]


# 9.How to print the all values of an array.

In [61]:

neelam_array = np.array([25,5848,596,2597,2317415])


for value in neelam_array:
    print(value)


25
5848
596
2597
2317415


# 10.Subtract the mean of each row of a matrix.

In [63]:

g= np.array([[85, 245, 33], [98, 54, 76],[70, 68, 29]])


row_means = np.mean(g, axis=1, keepdims=True)


normalized_matrix = g - row_means

print("Original Matrix:")
print(g)

print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[ 85 245  33]
 [ 98  54  76]
 [ 70  68  29]]

Matrix with Row Means Subtracted:
[[-36.         124.         -88.        ]
 [ 22.         -22.           0.        ]
 [ 14.33333333  12.33333333 -26.66666667]]


# 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)

In [67]:
p = np.array([10, 85, 856, 480, 569])


index_vector = np.array([1, 3, 3, 4, 0])


result_vector = p.copy()


unique_indices = np.unique(index_vector)


result_vector[unique_indices] += 1

print("p :")
print(p)

print("\nIndex Vector:")
print(index_vector)

print("\nResult Vector:")
print(result_vector)


p :
[ 10  85 856 480 569]

Index Vector:
[1 3 3 4 0]

Result Vector:
[ 11  86 856 481 570]


# 12. How to get the diagonal of a dot produt.

In [68]:
u = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])


dot_product = np.dot(u, v)


diagonal_elements = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal Elements of the Dot Product:")
print(diagonal_elements)


Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]

Diagonal Elements of the Dot Product:
[30 69 90]


# 13.How to find the most frequent value in an array.

In [70]:
arr = np.array([24,28,2,5,8,4,5,5,6,9,7,4,5,5,9,8,1,222,7,4,8,7,7,8,5,7,9,5,5,4,2,8,])



unique_values, counts = np.unique(arr, return_counts=True)


max_count_index = np.argmax(counts)


most_frequent_value = unique_values[max_count_index]

print("Array:", arr)
print("Most frequent value:", most_frequent_value)
print("Frequency:", counts[max_count_index])


Array: [ 24  28   2   5   8   4   5   5   6   9   7   4   5   5   9   8   1 222
   7   4   8   7   7   8   5   7   9   5   5   4   2   8]
Most frequent value: 5
Frequency: 8


# 14.How to get the n largest values of ana array

In [72]:
arr = np.array([45,25,55,88,44,66,88,7,5,4,6,58,4,1,2,5,7,8,55,411,2,6,54,7,55,9444,2])


n = 3


n_largest_values = np.partition(arr, -n)[-n:]

print("Array:", arr)
print(f"{n} Largest Values:", n_largest_values)


Array: [  45   25   55   88   44   66   88    7    5    4    6   58    4    1
    2    5    7    8   55  411    2    6   54    7   55 9444    2]
3 Largest Values: [  88  411 9444]


# 15.How to create a record array from a regular array

In [73]:


regular_array = np.array([("govind", 35), ("pavan", 40), ("shrini", 42)],
                         dtype=[('name', 'U10'), ('age', int)])


record_array = np.rec.fromarrays(regular_array.T, names="name,age")

print("Regular Array:")
print(regular_array)

print("\nRecord Array:")
print(record_array)#


Regular Array:
[('govind', 35) ('pavan', 40) ('shrini', 42)]

Record Array:
(('govind', 35), ('pavan', 40), ('shrini', 42))


# 16.How to swap two rows of an array

In [76]:
m = np.array([[101, 25, 73],[48, 95, 86],[79, 85, 98]])


row1 = 0  
row2 = 2  

temp_row = m[row1].copy()  
m[row1] = m[row2]  
m[row2] = temp_row  

print("Original Array:")
print(m)


Original Array:
[[ 79  85  98]
 [ 48  95  86]
 [101  25  73]]


# 17. Write python code to reshape to the next dimension of numpy array

In [81]:

original_array = np.array([15, 82, 32, 24, 45, 46])


next_dimension_size = (2, 3)


reshaped_array = original_array.reshape(next_dimension_size)

print("Original Array:")
print(original_array)

print("\nReshaped Array:")
print(reshaped_array)


Original Array:
[15 82 32 24 45 46]

Reshaped Array:
[[15 82 32]
 [24 45 46]]
