# Bag of Words

In [3]:
from sklearn.feature_extraction.text import CountVectorizer

text=['aba decides against community broadcasting licence','act fire witnesses must be aware of defamation',
'a g calls for infrastructure protection']

      
vectorizer=CountVectorizer()

      
x=vectorizer.fit_transform(text)

feature_names=vectorizer.get_feature_names_out()
    
print('Feature names:\n',feature_names)
      
print('Bow Matrix:\n')
      
print(x.toarray())
      
      

Feature names:
 ['aba' 'act' 'against' 'aware' 'be' 'broadcasting' 'calls' 'community'
 'decides' 'defamation' 'fire' 'for' 'infrastructure' 'licence' 'must'
 'of' 'protection' 'witnesses']
Bow Matrix:

[[1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0 0 0]
 [0 1 0 1 1 0 0 0 0 1 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1 0]]


# N-grams

In [5]:
import nltk
from nltk import ngrams

text='call for ethanol blend fuel to go ahead'

tokens=nltk.word_tokenize(text)
n=2
bigrams=list(ngrams(tokens,n))

print(f"Original text:{text}")
print(f"generated {n}-grams:")

for gram in bigrams:
    print(gram)

    

Original text:call for ethanol blend fuel to go ahead
generated 2-grams:
('call', 'for')
('for', 'ethanol')
('ethanol', 'blend')
('blend', 'fuel')
('fuel', 'to')
('to', 'go')
('go', 'ahead')


In [6]:
import nltk
from nltk import ngrams

text='barca take record as robson celebrates birthday in'

tokens=nltk.word_tokenize(text)
n=5
bigrams=list(ngrams(tokens,n))

print(f"Original text:{text}")
print(f"generated {n}-grams:")

for gram in bigrams:
    print(gram)

Original text:barca take record as robson celebrates birthday in
generated 5-grams:
('barca', 'take', 'record', 'as', 'robson')
('take', 'record', 'as', 'robson', 'celebrates')
('record', 'as', 'robson', 'celebrates', 'birthday')
('as', 'robson', 'celebrates', 'birthday', 'in')


In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

text=['air nz strike to affect australian travellers','big hopes for launceston cycling championship','businesses should prepare for terrorist attacks']

tfidf=TfidfVectorizer()
x_tfidf=tfidf.fit_transform(text)

features_names_tfidf=tfidf.get_feature_names_out()

print('Feature Names(TF-IDF):]\n',features_names_tfidf)
print('TF-IDF Matrix:\n',x_tfidf.toarray())




Feature Names(TF-IDF):]
 ['affect' 'air' 'attacks' 'australian' 'big' 'businesses' 'championship'
 'cycling' 'for' 'hopes' 'launceston' 'nz' 'prepare' 'should' 'strike'
 'terrorist' 'to' 'travellers']
TF-IDF Matrix:
 [[0.37796447 0.37796447 0.         0.37796447 0.         0.
  0.         0.         0.         0.         0.         0.37796447
  0.         0.         0.37796447 0.         0.37796447 0.37796447]
 [0.         0.         0.         0.         0.42339448 0.
  0.42339448 0.42339448 0.32200242 0.42339448 0.42339448 0.
  0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.42339448 0.         0.         0.42339448
  0.         0.         0.32200242 0.         0.         0.
  0.42339448 0.42339448 0.         0.42339448 0.         0.        ]]


# One Hot encoding

In [12]:
from sklearn.preprocessing import OneHotEncoder

import numpy as np

text=['govt is to blame for ethanols unpopularity oppgroup to meet in north west wa over rock ar','hacker gains access to eight million credit cards']

tokens=[word for sent in text for word in sent.lower().split()]

vocabulary=list(set(tokens))

encoder=OneHotEncoder(categories=[vocabulary],sparse=False)

one_hot_encoded=[]
for sent in text:
    sent_encoded=[]
    for word in sent.lower().split():
        word_index=vocabulary.index(word)
        word_vector=np.zeros(len(vocabulary))
        word_vector[word_index]=1
        sent_encoded.append(word_vector)
    one_hot_encoded.append(sent_encoded)
    
for sent in one_hot_encoded:
    print(sent)
    


[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0.]), array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.]), array([0., 0., 1., 0., 0., 

In [13]:
len(sent)


8